name = "portofolio"
pages_build_output_dir = "dist"
compatibility_date = "2026-04-03"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[build_context]
production = { command = "npm install && npm run build" }
preview = { command = "npm install && npm run build" }
